apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: insights-content-template-renderer
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/gbenhaim-tenant/insights-content-template-renderer/insights-content-template-renderer@sha256:536b8213a355ca363d90703a2b5391463a2d5692b85d84a8842a229acd9d4ec1
        name: container-image
        resources: {}
status: {}
