apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: insights-content-template-renderer
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: insights-content-template-renderer
    app.kubernetes.io/part-of: insights-content-template-renderer
  name: insights-content-template8zt0
spec:
  port:
    targetPort: 8000
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: insights-content-template-renderer
    weight: 100
status: {}
