apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: insights-content-template-renderer
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: insights-content-template-renderer
    app.kubernetes.io/part-of: insights-content-template-renderer
  name: insights-content-template-renderer
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: insights-content-template-renderer
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: insights-content-template-renderer
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/gbenhaim-tenant/insights-content-template-renderer/insights-content-template-renderer@sha256:3b2d84415351fc970f5f6e81dedd747074199bf1cb9d0b4bf1f247ff1a4391df
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
